// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from kaka.djinni

package com.lieluobo.kaka;

/** ./djinni/src/run --ident-jni-file jni_foo_bar --java-out kaka/proto/java/com/lieluobo/kaka --java-package com.lieluobo.kaka --cpp-out kaka/proto/gen_cpp --jni-out kaka/proto/gen_jni  --jni-base-lib-include-prefix djinni/support-lib/jni/  --idl kaka/proto/kaka.djinni */
public final class WordT {


    /*package*/ final String word;

    /*package*/ final long tag;

    /*package*/ final int start;

    /*package*/ final int end;

    public WordT(
            String word,
            long tag,
            int start,
            int end) {
        this.word = word;
        this.tag = tag;
        this.start = start;
        this.end = end;
    }

    public String getWord() {
        return word;
    }

    public long getTag() {
        return tag;
    }

    public int getStart() {
        return start;
    }

    public int getEnd() {
        return end;
    }

    @Override
    public String toString() {
        return "WordT{" +
                "word=" + word +
                "," + "tag=" + tag +
                "," + "start=" + start +
                "," + "end=" + end +
        "}";
    }

}
